
services:
  postgres:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - ./db:/var/lib/postgres
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: app
    depends_on: 
      - postgres
    build: ./src
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_NAME=$POSTGRES_NAME
    ports:
      - "9000:3000"
    volumes:
      - .:/app

  migraine-app:
    container_name: migraine-app
    depends_on:
      - postgres
      - app
    build: ./migraine-app
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/migraine-app
    command: npm start

volumes: 
  db: